### ISSUE TITLE
致命错误

### ISSUE THREAD

**Issue by BluecityS** [MoePlayer/Hermit-X#100]
博客废了
Parse error: syntax error, unexpected '[' in /home/ftp/s/s4466927/wwwroot/wp-content/plugins/Hermit-X-master/class.hermit.php on line 209

**Comment by fly3949** [comment]
@BluecityS 请升级 PHP 版本或尝试将代码中所有以“[]”定义数组的方法改成“Array(...)”

**Comment by fly3949** [comment]
#https://github.com/metowolf/Meting/issues/10

**Comment by fly3949** [comment]
请升级到 PHP 5.4 以上版本...
