### ISSUE TITLE
播放器列表默认折叠吧，要不然添加多首歌曲默认是展开的，要手动点击折叠

### ISSUE THREAD

**Issue by jozxing** [MoePlayer/Hermit-X#104]
播放器列表默认折叠吧，要不然添加多首歌曲默认是展开的，要手动点击折叠

**Comment by liwanglin12** [comment]
@jozxing 完成 AP 1.8 的升级工作后会在设置面板提供选项的，目前你也可以通过限制全局列表高度来优化视觉体验。

**Comment by liwanglin12** [comment]
Added. https://github.com/MoePlayer/Hermit-X/commit/9837bd6686ad9e4b5ea80a2805d45c04ee1390fa
