### ISSUE TITLE
新版本js代码有问题

### ISSUE THREAD

**Issue by mashirozx** [MoePlayer/Hermit-X#106]
压缩后前端js全部完蛋
![1.PNG](https://i.loli.net/2018/03/25/5ab70b700a6ce.png)

原因是你这里忘记转义了吧
![2.PNG](https://i.loli.net/2018/03/25/5ab70b6fe73e0.png)

一个小小的建议：通过WordPress官方渠道更新，或者提供一个是否启用自动更新的选项，否则更新出了任何问题站长很难及时处理的 :)

**Comment by liwanglin12** [comment]
@mashirozx 前端 js 压缩本来就会有各种各样的问题。。并不建议你去压缩 js 文件。

转义的这个问题请 @DIYgod 确认一下，另外建议你关闭 js 压缩并启用 HTTP/2，使用 HTTP/2 后请求数将不会是一个拖慢速度的因素。

WordPress 官方的更新用 SVN 做版本控制，太麻烦了，不是非常想用。保证邮件是通的就可以了，会给您发送更新报告的。

自动更新选项会考虑一下，优先级不会太高。主要是目前的更新率太低，导致我们的各种更新内容推进困难。

**Comment by mashirozx** [comment]
确认了，就是这行的问题
```
console.log(`\n %c Hermit X Music Helper v` + HermitX.version + ` %c https://lwl.moe/HermitX \n`, `color: #fff; background: #4285f4; padding:5px 0;`, `background: #66CCFF; padding:5px 0;`);
```
移除后代码压缩工作正常

**Comment by mashirozx** [comment]
![11.PNG](https://i.loli.net/2018/03/25/5ab70ecc8ff09.png)

![22.PNG](https://i.loli.net/2018/03/25/5ab70ecc8e635.png)

**Comment by Genteure** [comment]
@mashirozx 反引号 ` 是es6语法，压缩压坏了 🌝

**Comment by liwanglin12** [comment]
@mashirozx 已经确认是因为一个 ES6 语法未编译的问题，稍后就会修复。

另外 建议取消 JS 压缩/合并，尤其是你的 JS 压缩器不支持 ES6 语法的情况下

**Comment by mashirozx** [comment]
是的，建议仍然使用普通引号
```
console.log("\n %c Hermit X Music Helper v" + HermitX.version + " %c https://lwl.moe/HermitX \n", "color: #fff; background: #4285f4; padding:5px 0;", "background: #66CCFF; padding:5px 0;");
```

**Comment by liwanglin12** [comment]
一会儿改好了我来关闭吧~

另外……
![image](https://user-images.githubusercontent.com/10279535/37871212-716cb7d0-301b-11e8-971f-98df742dbc35.png)

![image](https://user-images.githubusercontent.com/10279535/37871214-823ddea4-301b-11e8-9c07-375f28bb9b60.png)

**Comment by mashirozx** [comment]
莓穿女装+1 （莓字什么时候排我输入法第一了
