### ISSUE TITLE
能不能添加一个连接跳转功能和自定义封面功能可以付费有偿

### ISSUE THREAD

**Issue by EForinaJ** [MoePlayer/Hermit-X#110]
就是有点功能需求，能不能添加一个连接跳转功能和自定义封面功能可以付费有偿

**Comment by liwanglin12** [comment]
@EForinaJ 链接跳转是什么意思？

**Comment by EForinaJ** [comment]
就是点击播放器上的歌曲名字跳转到该音乐的地址

**Comment by EForinaJ** [comment]
可以添加我QQ356866114 私聊

**Comment by EForinaJ** [comment]
@liwanglin12 就是点击播放器上的歌曲名字跳转到该音乐的地址  可以添加我QQ356866114 私聊

**Comment by liwanglin12** [comment]
Duplicated #18
