### ISSUE TITLE
本地音乐库后台页面选择相应类别的音乐列表，没有分页，还是所有歌曲的分页

### ISSUE THREAD

**Issue by cypcpycy** [MoePlayer/Hermit-X#113]

**Comment by liwanglin12** [comment]
不太明白您的意思？可以再具体描述一下吗

**Comment by cypcpycy** [comment]
我的意思是在后台页面不是有个音乐库么，所有添加的本地音乐都会列出来，然后分页是分的全部音乐，如果我设置类别就不识别限定类别的分类。比如本地音乐有一百首，30首古典音乐，30首民谣音乐，30首流行乐，10首摇滚乐，当我只想看那三十首古典音乐时候我就需要点击类别导航的古典音乐，然后列出了三十首古典音乐的第一页，我点第二页时候，就会变成全部100首音乐的第二页，没有做到导航分类，我不知道这么说你明白么，我也不太会用hub，要是能截图就好了，特别感谢你做的插件让我的网站有了音乐整理发布的工具，我对插件也根据自己需求进行了部分修改，有兴趣想和你交流下，我的微信号：327771296，有兴趣加我微信咱们交流

**Comment by liwanglin12** [comment]
@cypcpycy 您可以把您的改动提交 Pull Request 给我们，具体方法见 https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BA-Pull-Request 。 感谢贡献~

**Comment by cypcpycy** [comment]
我是很想pull，但是原谅我的笨拙，我一时间看不太懂怎么pull，是不是得搭建git环境，我就不会弄这个，我其实已经建立了两个文件，但是不知道你看不看得见

**Comment by liwanglin12** [comment]
@cypcpycy 我看了下你 fork 的库，你暂时还没有 Pull 上去。
https://github.com/xirong/my-git/blob/master/how-to-use-github.md 看下这个

**Comment by cypcpycy** [comment]
现在呢？我好想上传了我的版本分支，你看看有么

**Comment by liwanglin12** [comment]
@cypcpycy 看到了，你现在打开 Hermit X 仓库应该能在页面上看到一个发起 Pull Request 的按钮= =

**Comment by cypcpycy** [comment]
还有，我的更改要依赖插件：Add From Server，并且我对这个插件也进行了一些更改

**Comment by cypcpycy** [comment]
你看看现在有了么，我好像已经pull了

**Comment by cypcpycy** [comment]
恩，我这里做了许多更改，而且得依赖我改的另一个插件，我怎么传给你，还有我想问下，咱们插件有全站播放功能了么？

**Comment by cypcpycy** [comment]
翻页问题我在我的这个版本已经解决了，你看看这个思路行不行，json的返回我其实是没有刷出来，我是禁用了验证功能的，因为我没有找到md5的验证机制，所以你看看如果ok就给改完善吧
