### ISSUE TITLE
MIUI默认浏览器无法播放音乐

### ISSUE THREAD

**Issue by LongLights** [MoePlayer/Hermit-X#116]
报错如图，chrome和qq浏览器都是正常的。
![](https://i.loli.net/2018/07/03/5b3b653eb4c3e.png)

**Comment by LongLights** [comment]
除了miui的浏览器，发现在chrome和其他浏览器(PC端)下，如果开了蓝灯，网易云的音乐无法播放，qq音乐正常

**Comment by liwanglin12** [comment]
@LongLights 网易云海外 cdn ssl 有点问题所以是这样的

**Comment by LongLights** [comment]
@liwanglin12 发现了。。。直接访问网易云官网也是这样，而且是概率性的，有时候蓝灯分配的节点就没问题。所以miui那个问题定位了吗。。。

**Comment by lwl12** [comment]
请问这个问题现在还存在吗？目前这边没有 MIUI 测试环境

**Comment by LongLights** [comment]
@lwl12 已不存在了
