### ISSUE TITLE
wp文章编辑页使用插件时触发的bug

### ISSUE THREAD

**Issue by LongLights** [MoePlayer/Hermit-X#117]
在文章编辑呼出窗口的时候。有时候“qq音乐”那栏会要求输入“百度音乐”的链接，然后切回“网易云”的时候，会提示输入“qq音乐”的地址，希望作者可以完善一下。触发该bug时，环境为php7.2

**Comment by liwanglin12** [comment]
It may take long time to fix because I have too less time to maintaince this plugin.

**Comment by LongLights** [comment]
Nothing,its not serious.Cant affect my daily use.

**Comment by Copay** [comment]
@liwanglin12 too less?
There may be a syntax error.

**Comment by milkice233** [comment]
@LongLights Could you please provide more details? For example, what tabs had you selected in turn when this bug occurred?

**Comment by LongLights** [comment]
@milkice233 ![](https://i.loli.net/2018/07/04/5b3ccccc40e92.png)
![](https://i.loli.net/2018/07/04/5b3ccccc61757.png)

you can see from the pics.I choose Tencent music tab,but actually i have to insert Baidu Music url into it.And if i choose Netease tab,i have to insert tencent url.

**Comment by Copay** [comment]
Can't reproduce the bug.Please provide the detail on how it appears.

**Comment by milkice233** [comment]
@Copay It's easy to reproduce it as you have to first select '歌单' box for example in Netease Music Tab and then click Tencent Music Tab and then select whichever box you want under the tabs. After several clicks you'll see that the placeholder text below is not relevant to the selected tabs. I have reproduced this issue.

**Comment by lwl12** [comment]
Fixed #118.
