### ISSUE TITLE
听不了歌。。。

### ISSUE THREAD

**Issue by linyujue** [MoePlayer/Hermit-X#122]
我在edge浏览器上使用根本没有加载出播放器来。。。
播放的是媒体库的本地音乐，有60首。提示an audio error has occurred等等

**Comment by Copay** [comment]
请提供example

**Comment by linyujue** [comment]
我想应该不关乎edge的事情，因为firefox也无法使用。
Windows10/Windowsserver2012/iphone都试过，听不了
iPhone是根本无法加载
![image](https://user-images.githubusercontent.com/42398191/44140893-16c52f8e-a0ae-11e8-8dcd-443cd4181918.png)
![image](https://user-images.githubusercontent.com/42398191/44140927-36c87a98-a0ae-11e8-9d9f-c82f38553bf9.png)

**Comment by linyujue** [comment]
Edge16

**Comment by lwl12** [comment]
由于你是本地环境，我们这边没有办法查看具体情况，请提供浏览器开发者工具 Console 里的报错信息以供排查。

**Comment by linyujue** [comment]
![image](https://user-images.githubusercontent.com/42398191/44145959-148dc570-a0c0-11e8-9aca-7641fed9ca2b.png)

**Comment by lwl12** [comment]
停用除了 Hermit X 的所有插件再试试

**Comment by linyujue** [comment]
刚刚试了，依然如此。。。

**Comment by lwl12** [comment]
看起来可能是返回的 json 有问题……你能放到线上试试么

**Comment by linyujue** [comment]
http://172.81.239.61/wordpress/

**Comment by lwl12** [comment]
@linyujue 在 WordPress 设置里把站点 url 改成你这个 差评

**Comment by linyujue** [comment]
sorry我没有域名。。。主要是域名未认证

**Comment by linyujue** [comment]
![image](https://user-images.githubusercontent.com/42398191/44146562-ba7dbf42-a0c2-11e8-805d-30b84b8e9e48.png)

**Comment by linyujue** [comment]
改了

**Comment by linyujue** [comment]
不行。。。

**Comment by Copay** [comment]
@linyujue 刚看了一下，ta的url都是可定位到歌曲的

**Comment by lwl12** [comment]
@Copay 嗯我也看到了，我这边只是因为 hx 的缓存目前还没有办法让播放器正常播放，但是我看除了歌曲 url 指错了以外没有其他错误了……感觉应该没什么问题啊

**Comment by linyujue** [comment]
我是本地歌曲。不过那为什么不行？

**Comment by Copay** [comment]
@linyujue 只能看细节了
也许是播放器的bug之类
但是你得先给个能用的example

**Comment by linyujue** [comment]
无example，要啥example

**Comment by Copay** [comment]
@linyujue 问题复现供我们调试……
如果问题无法复现，我们也无法解决问题呀。

**Comment by linyujue** [comment]
我发现问题了。。。。

**Comment by linyujue** [comment]
我嫌歌曲一首一首添加地太麻烦，用navicat把60首一下添进了hermit数据库里
估计是其他参数没设置

**Comment by lwl12** [comment]
@linyujue ……

**Comment by lwl12** [comment]
@linyujue 但是看起来不像这种问题

**Comment by linyujue** [comment]
![image](https://user-images.githubusercontent.com/42398191/44147207-b55052ac-a0c5-11e8-8d70-4ca527f11546.png)

**Comment by linyujue** [comment]
可是事实在这里，我从媒体库里新添加到音乐库的歌曲可以播放

**Comment by linyujue** [comment]
对照实验

**Comment by fly3949** [comment]
数据库里的`localhost`换成你的ip试试（

**Comment by linyujue** [comment]
好

**Comment by Copay** [comment]
这都甚么搞法

**Comment by linyujue** [comment]
因为懒癌。。。我不想一首一首添进库里

**Comment by linyujue** [comment]
然后我是在localhost里编辑wordpress的

**Comment by fly3949** [comment]
那大概是你现在的歌无法通过`localhost`那个地址访问吧...数据库里的歌曲地址改一下就可以了

**Comment by Copay** [comment]
🌚

**Comment by linyujue** [comment]
对对对
我马上改
谢谢

**Comment by linyujue** [comment]
对了就是这样！！

**Comment by lwl12** [comment]
@fly3949 tql %%%

**Comment by fly3949** [comment]
好的(●ˇ∀ˇ●)

**Comment by linyujue** [comment]
再问个问题：请问能不能隐藏播放器？就当背景音乐

**Comment by Copay** [comment]
@linyujue display: none;
