### ISSUE TITLE
不兼容wordpress5.0的新编辑器

### ISSUE THREAD

**Issue by bafflingbug** [MoePlayer/Hermit-X#134]
- wordpress v5.0使用了新的编辑器，Hermit-X在新的编辑器上找不到新的“添加音乐”的按钮
详情见 https://wordpress.org/support/wordpress-version/version-5-0/
----
临时解决方案：安装 Classic Editor 插件使用传统编辑器

**Comment by lwl12** [comment]
怕啥来啥……还是有人来问了（逃

已经在尝试兼容当中了，但是我们缺开发人手所以进度可能会比较慢
![image](https://user-images.githubusercontent.com/10279535/49986411-cd60da80-ffaa-11e8-8f6a-8f5e75455340.png)

**Comment by bafflingbug** [comment]
看了下文档，好像要注册一个block。有空我去尝试一下:)

**Comment by lwl12** [comment]
@bafflingbug 建议先等等（（（别等下功能撞车了

**Comment by yrccondor** [comment]
@bafflingbug 我们经在着手适配了，不过可能还需要一点时间

**Comment by bafflingbug** [comment]
@yrccondor  @lwl12 👌

**Comment by yhyates** [comment]
可以先停用新编辑器曲线救国，functions里加入add_filter( 'use_block_editor_for_post', '__return_false', 999 );
remove_action( 'wp_enqueue_scripts', 'wp_common_block_scripts_and_styles' );，即可用回旧编辑器

**Comment by yrccondor** [comment]
@yhyates 已经在适配中了，还需要一点时间

**Comment by bafflingbug** [comment]
> 可以先停用新编辑器曲线救国，functions里加入add_filter( 'use_block_editor_for_post', '__return_false', 999 );
> remove_action( 'wp_enqueue_scripts', 'wp_common_block_scripts_and_styles' );，即可用回旧编辑器

对于使用旧的编辑器的话，可以尝试安装`经典编辑器`这个插件。这应该是官方推荐的方法

**Comment by yrccondor** [comment]
@bafflingbug 一刀切禁用新编辑器是不可取的；安装 Classic Editor 这个插件后即可自由切换

**Comment by bafflingbug** [comment]
> @bafflingbug 一刀切禁用新编辑器是不可取的；安装 Classic Editor 这个插件后即可自由切换

我知道啊，你回复错人了

**Comment by yrccondor** [comment]
@bafflingbug 抱歉，推到 Telegram 上后看错了

**Comment by syfxlin** [comment]
昨天写文章到处找不到添加按钮。。。我已为Hermit-X添加了Gutenberg的支持，已发Pull Request。ヾ(≧▽≦*)o
