### ISSUE TITLE
Support specific album cover url for given music

### ISSUE THREAD

**Issue by BlueCocoa** [MoePlayer/Hermit-X#18]
Hermit X could load album cover automatically for online music, which is awesome. However, for local music, there's only default album cover. 

Hermit X would be more perfect if we could specify album cover url for given music. ☆〜（ゝ。∂）

**Comment by liwanglin12** [comment]
@BlueCocoa 😂 so you failed at this issue?

**Comment by BlueCocoa** [comment]
Yes...😂

P.S 

If assume that users only get updated by class.update.php, the issue is easier to solve. 
But if there's any user who updates Hermit X by hand, it's a little bit hard to deal with.

**Comment by liwanglin12** [comment]
@BlueCocoa 🌚that's possible. but maybe we can detected if database have field ... by scheduled tasks

**Comment by SakuraLove** [comment]
突如其来地撞到bluecocoa大佬

**Comment by liwanglin12** [comment]
@Bing072 是否有时间添加一个数据库结构更新呢，如果没有的话就把这个 issue 关闭掉吧。

**Comment by sarabear** [comment]
同样希望能支持本地音乐支持封面图啊。 因为新增本地歌曲时没办法设置歌曲图片，于是现在只能简单写死返回的封面图都是同一个了。 总比默认颜色的好那么一点点

**Comment by cypcpycy** [comment]
这个封面问题我已经解决了，在我的版本里面有的，封面是要用后台上传到媒体库

**Comment by lwl12** [comment]
Added. #124
