### ISSUE TITLE
可不可以在设置中加入默认音量的设置

### ISSUE THREAD

**Issue by SakuraLove** [MoePlayer/Hermit-X#71]
可不可以在设置中加入默认音量的设置
感觉默认音量有点太大，会吓到人2333

**Comment by DIYgod** [comment]
使用 `ap.volume(percentage)` 这个 API，或者调低你的设备音量，或者处理下音频

**Comment by liwanglin12** [comment]
<script>window.APlayerCall = []; window.APlayerCall[1] = function () {setTimeout(function(){ap[1].volume(percentage);},50);}</script>
