### ISSUE TITLE
控制台报错：Uncaught TypeError

### ISSUE THREAD

**Issue by zwillhill** [MoePlayer/Hermit-X#74]
wp未登陆状态错误：

> Uncaught TypeError: Cannot read property 'classList' of undefined
>     at XMLHttpRequest.o.onreadystatechange (APlayer.min.js:1)
> o.onreadystatechange @ APlayer.min.js:1
> XMLHttpRequest.send (async)
> value @ APlayer.min.js:1
> e @ APlayer.min.js:1
> xhr.(anonymous function).onreadystatechange @ (index):413
> XMLHttpRequest.send (async)
> hermitInit @ (index):413
> (anonymous) @ (index):413

wp已登陆状态（管理员账号）错误：

> Uncaught TypeError: Cannot read property 'classList' of undefined
>     at XMLHttpRequest.o.onreadystatechange (APlayer.min.js:1)
> o.onreadystatechange @ APlayer.min.js:1

不过都可以正常播放音乐

**Comment by fly3949** [comment]
@zwillhill 方便提供下网站地址吗

**Comment by zwillhill** [comment]
@fly3949 xiabm.com

**Comment by liwanglin12** [comment]
@DIYgod @fly3949  follow-up required

**Comment by DIYgod** [comment]
@zwillhill I can not access your website.

**Comment by liwanglin12** [comment]
@DIYgod My site has same issue...

**Comment by robin-zhao** [comment]
作者你好，

偶然发现你的插件，装上后遇到同样问题

Uncaught TypeError: Cannot read property 'classList' of undefined
    at XMLHttpRequest.o.onreadystatechange (APlayer.min.js?ver=2.6.6.1101-RC:1)

和上面反馈的不一样，我**播放不了**。只有一个一秒的音频 叮叮叮的在播放。。。

大概是这一行：
     **t.lrcContents.getElementsByTagName("p")[0].classList.add("aplayer-lrc-current"),**

我建了个demo页面，麻烦看下是什么问题：
https://blog.54zxy.com/test-only/   ： 密码是  123

谢谢！

**Comment by robin-zhao** [comment]
OK.

不用管我上面一条评论。我播放不了大概是因为我的服务器在DO上， curl不到国内音频地址。

```
GET https://api.lwl12.com/music/netease/song?id=607441 net::ERR_INSECURE_RESPONSE
APlayer.min.js?ver=2.6.6.1101-RC:1 Uncaught (in promise) DOMException: The element has no supported sources.
```


```
        $url = json_decode($Meting->format()->url($music_id, $this->settings('quality')), true);
        $url = $url['url'];

        if (empty($url)) {
            Header("Location: " . 'https://api.lwl12.com/music/netease/song?id=607441');
            exit;
        }

```

URL 没取到 为空了。

真是尴尬。评论我就不删了，万一有谁也尝试国外服务器用本插件，可以停止浪费时间了。

**Comment by liwanglin12** [comment]
@robin-zhao 其实道理上国外应该能用的，让 @metowolf 查一下吧

**Comment by kn007** [comment]
@robin-zhao 因为作者服务器被人打宕机了，你可以换个时间试试，谢谢

**Comment by liwanglin12** [comment]
@kn007 和这个没关系，不要乱回复

**Comment by liwanglin12** [comment]
Fixed. https://github.com/MoePlayer/Hermit-X/commit/ed89facfe71669f5310a8ba08ac4afbf4985433d
