### ISSUE TITLE
好像经常会403无法播放？

### ISSUE THREAD

**Issue by zwillhill** [MoePlayer/Hermit-X#75]
[http://ww1.sinaimg.cn/large/45cf54fcly1fk1434c4otj20hu04b74w.jpg](url)
播放器界面经常出现“error happens”
[http://ww1.sinaimg.cn/large/45cf54fcly1fk143rwxgzj20em012q2q.jpg](url)
[http://ww1.sinaimg.cn/large/45cf54fcly1fk1440qxr0j216m0g5t99.jpg](url)
检查代码，貌似解析到的mp3被403了——切到其它歌偶尔有还能播放的。在插件设置中清空数据库缓存貌似能恢复一小段时间，再切换两三首歌就又不行了

**Comment by liwanglin12** [comment]
@zwillhill 有设置网易云cookies么？有的话是从哪里提取的？

**Comment by liwanglin12** [comment]
我们的测试结果显示并没有问题。。。
你能来 lwl12.com 试试么

**Comment by zwillhill** [comment]
@liwanglin12 没有设置网易云cookies（正如插件设置所说明：不会使用~~），刚才在https://blog.lwl12.com/read/hermit-x.html测试，没发现出错（但是记得在发issues前该页也有个别歌曲也经常被403，刷新下页面有时就能恢复正常）——另外，之前发过一个issue控制台报错的，贵站好像还有，我的站点反而没有了（可能和插件之类有冲突？最近卸载不少插件……）
[](http://ww1.sinaimg.cn/large/45cf54fcly1fk1n0x5796j216t0cojtj.jpg)
[](http://ww1.sinaimg.cn/large/45cf54fcly1fk1n0lrn5rj217d0dkgmz.jpg)。
被403的貌似也不是版权歌曲，比如太坦白 (Live) – 陈奕迅（[](http://music.163.com/#/song?id=32019255)），之前403，清掉缓存，貌似播放正常许多……
对了，用的浏览器是chrome，版本号61

**Comment by zwillhill** [comment]
@liwanglin12 ，应该是菜鸟如我，能用上这样的插件，谢谢你。之前直接用网易云的外链播放器，一方面是flash的，另一方面外链播放器里貌似调用了百度统计代码，被运营商猥琐的劫持广告了……

**Comment by zwillhill** [comment]
@liwanglin12 cookie里设置了JSESSIONID，貌似好多了

**Comment by liwanglin12** [comment]
初步调查结果是网易云新启用的 m8c CDN 有反盗链……导致无法播放
害我们还高兴了一阵海外 HTTPS 的问题解决了&……

**Comment by liwanglin12** [comment]
#2b61c65 fixed
