### ISSUE TITLE
播放器无法加载，401错误

### ISSUE THREAD

**Issue by fantastlcok** [MoePlayer/Hermit-X#78]
刚刚标题打错了，是401错误。还没来得及修改就被关闭了，真是神速。

GET https://acg18.us/wp-admin/admin-ajax.php?action=hermit&scope=netease_songlist&id=434981337&_nonce=3d47272b01 401 (Unauthorized)

为啥会出现这种情况呢，缓存原因？

**Comment by liwanglin12** [comment]
是缓存原因。
不可以有全页面级的缓存，nonce 参数是 48 小时有效的，而且对于不同的登录态也会改变

**Comment by fantastlcok** [comment]
我在48小时内刷新一次页面可行吗？

**Comment by liwanglin12** [comment]
有缓存的话要保证页面首次访问是未登录状态下发出的……如果拿管理帐号访问了的话未登录的用户就无法请求这个接口

**Comment by liwanglin12** [comment]
主要还是防止滥用的考虑= =

**Comment by fantastlcok** [comment]
@liwanglin12 目前，登录用户看到的缓存和游客的缓存是分开的，缓存最大时间是24H。但是依然会出现401的错误。

**Comment by liwanglin12** [comment]
![snipaste20171006_142808](https://user-images.githubusercontent.com/10279535/31265687-a773043c-aaa2-11e7-9179-e52987b51caa.png)
我这边 看到没有问题呢= =

**Comment by fantastlcok** [comment]
是的，游客访问暂时木有问题，登陆下访问401。既然知道了是时效问题，我缩短缓存寿命试试。

**Comment by liwanglin12** [comment]
不慌，我在改代码了，你等一下

**Comment by fantastlcok** [comment]
感谢，果然大佬体内都是肝。

**Comment by liwanglin12** [comment]
等 @metowolf 大佬 review 完更新就会自动推送了，他现在好像不在（逃

**Comment by liwanglin12** [comment]
看到你站点已经更新了，但是似乎问题没有解决。
需要手动去设置里打开“使用低安全性验证”

**Comment by fantastlcok** [comment]
啊，感谢大佬，已设置完毕。
