### ISSUE TITLE
不能解析腾讯的音乐是什么鬼？！

### ISSUE THREAD

**Issue by Yephy** [MoePlayer/Hermit-X#81]
如题，使用了贵插件，刚开始没有设置目录，直接以`Hermit-X-master`目录上传，结果发现插入音乐时，解析错误，后来，将目录改成`Hermit-X`，重新启动插件，OK，终于正常了！但是……
但是，因为腾讯在国内的歌曲拥有数量和版权地位，插入音乐一般都会优先选择腾讯的，结果在插入腾讯音乐的地方，输入链接后，居然……无法解析……怎么办？能更新解决这个问题么？难道是我插件目录不对？还是说我的网站开了Https的锅？！我另一个网站也是https用的Typecho程序，使用的Meting播放器，就可以正常添加解析腾讯的音乐……

**Comment by liwanglin12** [comment]
Please provide music url

**Comment by DIYgod** [comment]
@Yephy https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by Yephy** [comment]
比如，现在腾讯音乐的专辑地址为：
https://y.qq.com/n/yqq/album/002y0x8e3iON8S.html
https://y.qq.com/n/yqq/album/002j9VDs37zxdQ.html
歌曲链接形式为：
https://y.qq.com/n/yqq/song/001ztWCk4LMHJR.html
这样的链接形式，

**Comment by Yephy** [comment]
我那个Typecho使用的插件是METO开发的
https://github.com/MoePlayer/APlayer-Typecho
这个，是可以完美支持腾讯音乐添加解析的！

还有，兄弟加你Q了， 貌似你没在线？还是忙着没看到？！

**Comment by liwanglin12** [comment]
沟通问题使用 QQ 效率极低，咱也没有时间聊 QQ。实在很需要 QQ 的话按小时付费，50 CNY/h。
问题已确认，请等待修复。

**Comment by Yephy** [comment]
刚才顺便又去看了METO的项目介绍，发现，腾讯音乐之前的歌曲、专辑、歌单地址形式分别为：
QQ 音乐 http://y.qq.com
单曲 https://y.qq.com/portal/song/000jDQWP4JiB3y.html
专辑 https://y.qq.com/portal/album/003rytri2FHG3V.html
歌手 https://y.qq.com/portal/singer/003Nz2So3XXYek.html
歌单 https://y.qq.com/portal/playlist/1144188779.html
貌似现在腾讯改版了，METO的Typecho插件也更新了，但是说明文档没有更新，而新的腾讯音乐地址变成了：
单曲 https://y.qq.com/n/yqq/song/000jDQWP4JiB3y.html
专辑 https://y.qq.com/n/yqq/album/003rytri2FHG3V.html
歌手 https://y.qq.com/n/yqq/singer/003Nz2So3XXYek.html
歌单 https://y.qq.com/n/yqq/playlist/1144188779.html
所以才造成了解析错误？

**Comment by liwanglin12** [comment]
https://github.com/MoePlayer/Hermit-X/commit/df706a38e9871b0c7edd8e0da6324c34f0b27703 Fixed.
