### ISSUE TITLE
播放器在文章中要刷新一次才能显示

### ISSUE THREAD

**Issue by LALADevil** [MoePlayer/Hermit-X#86]
复现地址：http://cautious-peacock.w5.poopy.life/2017/12/03/music-player-test/

求大佬解救QAQ

**Comment by liwanglin12** [comment]
我这边看首次打开就可以看到啊

**Comment by LALADevil** [comment]
@liwanglin12 火狐浏览器没问题，换了几个Chromium内核的浏览器都是第一次不能显示，刷新一下才行。

**Comment by liwanglin12** [comment]
@LALADevil 我这 Chrome 62.0.3202.94 没问题

**Comment by LALADevil** [comment]
= =灵异了。。。

**Comment by liwanglin12** [comment]
@LALADevil @DIYgod

**Comment by LALADevil** [comment]
大佬要不要多找几个人看看上面那个地址是不是这样，我觉得是我网络问题，但是我挂了个SS去访问还是一样，并且我的浏览器版本号也是Chrome 62.0.3202.94

**Comment by fly3949** [comment]
63.0.3239.70
首次打开正常

建议你开console然后看一下，有错误发上来看看

**Comment by fly3949** [comment]
64.0.3282.5 也是完全 ok 的

**Comment by LALADevil** [comment]
![2017-12-03-41-286](https://user-images.githubusercontent.com/33951857/33525737-b7340604-d870-11e7-86ee-201023e0b5cd.png)

**Comment by liwanglin12** [comment]
在后台检测一下更新，升级完再试试？

**Comment by LALADevil** [comment]
谢谢，更新后正常了。

**Comment by liwanglin12** [comment]
不客气。应该是你本地网络到你服务器的连线太慢了。
