### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by Hivol** [MoePlayer/Hermit-X#87]
在使用网易云的链接时，歌曲资源会出现403的错误，无法播放
虾米音乐的资源正常

是直接在Wordpress安装的插件，版本3.0.0

![image](https://user-images.githubusercontent.com/31159723/33663474-1d71a6a4-dacb-11e7-8edd-5cad775773ab.png)

**Comment by liwanglin12** [comment]
从截图来看你使用的是 Hermit 而非 Hermit X， 请联系 Hermit 作者牧风解决此问题。

 另外，Hermit X 并没有这个问题
![](https://user-images.githubusercontent.com/10279535/33664032-23f318f8-dacd-11e7-8c52-0dc94022d8ce.png)

**Comment by Hivol** [comment]
啊，不好意思！！ 对不起打扰了
