### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by mashirozx** [MoePlayer/Hermit-X#88]
如下，遇到这个的问题：

![image](https://user-images.githubusercontent.com/16148054/34303025-90635f0e-e76e-11e7-898d-2905c7f4d73e.png)

插件没又修改过，会不会是服务器配置的问题？

**Comment by liwanglin12** [comment]
请提供示例页面

**Comment by liwanglin12** [comment]
简单的看了一下你这个不知道为什么，请求歌单信息的接口直接返回了歌曲……
是你那边做了什么缓存吗？试试取消所有缓存看一下

**Comment by mashirozx** [comment]
我上了又拍云的CDN，你可以试试通过[这个](http://telegra.ph/hosts-12-22)hosts直连服务器，一切正常。

我也猜测又拍云哪里缓存了，但是试了一般天没找到问题

**Comment by liwanglin12** [comment]
@mashirozx 那建议再看看 upyun 的设置了……正常来说没道理缓存这个的，列表接口也不会直接跳转mp3，不知道这是怎么触发的
发个工单给生怕与你

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/34303447-5b15303c-e770-11e7-89a5-9e2172f72127.png)

**Comment by liwanglin12** [comment]
另外就是你站似乎没加 pjax 重载函数……

**Comment by liwanglin12** [comment]
加不缓存规则试试呢，把所有 `/wp-admin/admin-ajax.php?action=hermit` 的请求不缓存

**Comment by mashirozx** [comment]
似乎还是不行 <https://2heng.xin/syntaxerror/>

**Comment by mashirozx** [comment]
我先开工单问一下，谢谢哈 ^_^

**Comment by mashirozx** [comment]
你好，想请教一下 `/wp-admin/admin-ajax.php?action=hermit` 这个接口的实现原理是什么呢？
我原本以为应该是返回一个包含163的url的 JSON 文件。实在想不通又拍云是怎么解析出音乐的，现在我从又拍云那里得到的那个音乐文件到底是163的服务器下载的还是从又拍云下载的？

**Comment by liwanglin12** [comment]
我也很想不通up是怎么获取到的。你的理解没有问题，确实就是返回了带url和其他信息的一个json

Mashiro <notifications@github.com> 于 2017年12月23日周六 上午12:25写道：

**Comment by mashirozx** [comment]
emmm，很诡异。。。客服刚刚回复了，是因为这个原因，现在已经解决了

![image](https://user-images.githubusercontent.com/16148054/34306091-61f75356-e77c-11e7-924f-684febdc0212.png)
又拍云这个功能默认是开启的，按照客服说的用ftp删没有用，只能把这个源站资源迁移关闭了
![image](https://user-images.githubusercontent.com/16148054/34306123-7a3b78f2-e77c-11e7-80d0-2dc8ece94f4b.png)

PS. 你真的只是个高中生吗？这么厉害。。感觉我自己大概连大学都白读了吧😂

**Comment by liwanglin12** [comment]
😫解决了就好啦（
About 不作假的233
