### ISSUE TITLE
关于ssl兼容问题

### ISSUE THREAD

**Issue by bzpv2k** [MoePlayer/Hermit-X#92]
首先hermit是同类型插件中做的很出色的一。然后说问题，我的WP已实现全站https，用hermit插入网易云音乐歌曲地址“https:xxx”后小绿锁变黄，于是F12拔代码，发现歌曲的封面图片和一些其他资源来源于“http” 从而造成了小绿锁变黄…

**Comment by liwanglin12** [comment]
如果您确定你正在使用 Hermit X 而非 Hermit，并且您的站点后台设置内站点 url 已改为 https 协议，请提供演示链接以便核实。

**Comment by bzpv2k** [comment]
sorry，我应该使用的是Hermit而非Hermit X…。Hermit X好像未在Wordpress插件发布？

**Comment by liwanglin12** [comment]
是的，WordPress 官方库上架比较麻烦（有很多麻烦的文档要改），另外我们有自有的更新模式似乎没办法进官方库

**Comment by kn007** [comment]
Hermit请找牧风，已经停止维护了。
可以现在就尝试Hermit-X。

**Comment by liwanglin12** [comment]
看下这个也可以
https://kn007.net/topics/wordpress-blog-use-new-html5-player-aplayer/

**Comment by bzpv2k** [comment]
好的谢谢！

**Comment by yeniugo** [comment]
2.6.6.1101-RC版本，Hermit-X，官方插件中心下载的
