### ISSUE TITLE
https下Mixed Content

### ISSUE THREAD

**Issue by yeniugo** [MoePlayer/Hermit-X#95]
![image](https://user-images.githubusercontent.com/6367816/36073690-98569ba8-0f6f-11e8-8aa6-03d2d46187a0.png)

chrome下资源错误，不知道怎么办

**Comment by liwanglin12** [comment]
参见 #92

**Comment by yeniugo** [comment]
2.6.6.1101-RC版本，Hermit-X，官方插件中心下载的

**Comment by liwanglin12** [comment]
> 如果您确定你正在使用 Hermit X 而非 Hermit，**并且您的站点后台设置内站点 url 已改为 https 协议**，请提供演示链接以便核实。

**Comment by yeniugo** [comment]
下载位置有点不清除了，但看名字是Hermit-X，2.6.6.1101-RC版本，测试网址https://test.yeniugo.com

**Comment by liwanglin12** [comment]
换个歌单试试

**Comment by yeniugo** [comment]
好了，多谢
不过发现其它问题，QQ音乐加载单曲失败，https://test.yeniugo.com/64.html，原始地址有两个，都不行，https://y.qq.com/n/yqq/song/003i6DfD0Nxb3M.html，https://y.qq.com/n/yqq/song/98084_num.html，都加载失败。求解

**Comment by liwanglin12** [comment]
换歌单可行的话应该是缓存的问题，我看你改了一次站点 URL。
我看你现在这个单曲选了网易云……记得换选项卡 :-)

**Comment by yeniugo** [comment]
不好意思，因为之前一直用的下面那个音乐地址，上面那个地址是才找到的，看来地址需要注意了
