### ISSUE TITLE
amp页面加载问题

### ISSUE THREAD

**Issue by yeniugo** [MoePlayer/Hermit-X#99]
amp页面无法加载插件
使用了AMP插件后，AMP页面无法正常使用插件

**Comment by liwanglin12** [comment]
@yeniugo 请理解 AMP 是一个用于加速移动端访问的规范，因此 Hermit X 所需的 CSS / JS 文件在此环境下无法加载。
如果需要在 AMP 页面里插入音频，请查看 AMP 官方文档实现：https://www.ampproject.org/docs/reference/components/amp-audio
